# Generated by Django 4.2.7 on 2023-11-29 18:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laxout_Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution', models.CharField(default='', max_length=400)),
                ('name', models.CharField(default='', max_length=40)),
                ('dauer', models.IntegerField(default=30)),
                ('videoPath', models.CharField(default='', max_length=100)),
                ('looping', models.BooleanField(default=False)),
                ('added', models.BooleanField(default=False)),
                ('instruction', models.CharField(default='', max_length=200)),
                ('timer', models.BooleanField(default=False)),
                ('required', models.CharField(default='', max_length=50)),
                ('imagePath', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Laxout_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laxout_user_name', models.CharField(default='', max_length=200)),
                ('user_uid', models.CharField(default='', max_length=80)),
                ('access_code', models.CharField(default='', max_length=10)),
                ('laxout_credits', models.IntegerField(default=0)),
                ('creation_date', models.DateField(default=datetime.datetime(2023, 11, 29, 18, 52, 10, 76233, tzinfo=datetime.timezone.utc))),
                ('note', models.CharField(default='', max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercises', models.ManyToManyField(to='laxout_app.laxout_exercise')),
            ],
        ),
    ]
