# Generated by Django 4.2.7 on 2023-11-30 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxout_user',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 30, 18, 42, 15, 750961, tzinfo=datetime.timezone.utc)),
        ),
    ]
