# Generated by Django 4.2.7 on 2023-12-05 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0005_alter_laxout_user_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxout_user',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 5, 15, 4, 42, 46934, tzinfo=datetime.timezone.utc)),
        ),
    ]
