# Generated by Django 4.2.5 on 2023-12-06 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0008_alter_laxout_user_access_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxout_user',
            name='access_code',
            field=models.CharField(blank=True, default='LX-8797', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laxout_user',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 6, 14, 44, 46, 474464, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxout_user',
            name='user_uid',
            field=models.CharField(default='pnFP}JQCkF}ldo63xdKcWsI30KynpM>`vd,!gV98oTpMis13&j*KFT~P@20!6dC7,mo@W#Cs\\\\8^G:o:8%dK6qYx?x0r>]yL6C#S', max_length=80),
        ),
    ]
