# Generated by Django 4.2.5 on 2023-12-06 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0009_alter_laxout_user_access_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxout_user',
            name='access_code',
            field=models.CharField(blank=True, default='LX-9396', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='laxout_user',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 6, 14, 55, 17, 327862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxout_user',
            name='user_uid',
            field=models.CharField(default='uSud~U+;b@]fT`{wCiR]$tr0,k{72!ujH)R_r"8rZ{>Ac86faop8cDs}!+qWbI]XNU~zgM`;P2pe#e?LRlp`$_.$s$,UuVz~g/,B', max_length=80),
        ),
    ]
